
[functions.processar-inscricao]
enabled = true
verify_jwt = true
import_map = "./functions/processar-inscricao/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/processar-inscricao/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/processar-inscricao/*.html" ]

[functions.processar-checkin]
enabled = true
verify_jwt = true
import_map = "./functions/processar-checkin/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/processar-checkin/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/processar-checkin/*.html" ]
